# symbol_map.py

SYMBOL_MAP = {
    "ADANIENT": {
        "zerodha": {"trading_symbol": "ADANIENT", "exchange": "NSE", "token": "25"},
        "aliceblue": {"trading_symbol": "ADANIENT-EQ", "symbol_id": "25", "exch": "NSE"},
        "fyers": {"symbol": "NSE:ADANIENT-EQ", "token": "25"},
        "finvasia": {"symbol": "ADANIENT-EQ", "token": "25", "exchange": "NSE"},
        "dhan": {"security_id": "25", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "ADANIENT-EQ", "token": "25", "exchange": "NSE"},
        "acagarwal": {"symbol": "ADANIENT-EQ", "token": "25", "exchange": "NSE"},
        "motilaloswal": {"symbol": "ADANIENT", "token": "25", "exchange": "NSE"},
        "kotakneo": {"symbol": "ADANIENT", "token": "25", "exchange": "NSE"},
        "tradejini": {"symbol": "ADANIENT-EQ", "token": "25", "exchange": "NSE"},
        "zebu": {"symbol": "ADANIENT-EQ", "token": "25", "exchange": "NSE"},
        "enrichmoney": {"symbol": "ADANIENT-EQ", "token": "25", "exchange": "NSE"},
    },
    "IDEA": {
        "zerodha":      {"trading_symbol": "IDEA",       "exchange": "NSE", "token": "926241"},
        "aliceblue":    {"trading_symbol": "IDEA-EQ",    "symbol_id":  "926241", "exch": "NSE"},
        "fyers":        {"symbol": "NSE:IDEA-EQ",        "token": "926241"},
        "finvasia":     {"symbol": "IDEA-EQ",            "token": "926241", "exchange": "NSE"},
        "dhan":         {"security_id": "926241",        "exchange_segment": "NSE_EQ"},
        "flattrade":    {"symbol": "IDEA-EQ",            "token": "926241", "exchange": "NSE"},
        "acagarwal":    {"symbol": "IDEA-EQ",            "token": "926241", "exchange": "NSE"},
        "motilaloswal": {"symbol": "IDEA",               "token": "926241", "exchange": "NSE"},
        "kotakneo":     {"symbol": "IDEA",               "token": "926241", "exchange": "NSE"},
        "tradejini":    {"symbol": "IDEA-EQ",            "token": "926241", "exchange": "NSE"},
        "zebu":         {"symbol": "IDEA-EQ",            "token": "926241", "exchange": "NSE"},
        "enrichmoney":  {"symbol": "IDEA-EQ",            "token": "926241", "exchange": "NSE"},
    },

    "ADANIPORTS": {
        "zerodha": {"trading_symbol": "ADANIPORTS", "exchange": "NSE", "token": "15083"},
        "aliceblue": {"trading_symbol": "ADANIPORTS-EQ", "symbol_id": "15083", "exch": "NSE"},
        "fyers": {"symbol": "NSE:ADANIPORTS-EQ", "token": "15083"},
        "finvasia": {"symbol": "ADANIPORTS-EQ", "token": "15083", "exchange": "NSE"},
        "dhan": {"security_id": "15083", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "ADANIPORTS-EQ", "token": "15083", "exchange": "NSE"},
        "acagarwal": {"symbol": "ADANIPORTS-EQ", "token": "15083", "exchange": "NSE"},
        "motilaloswal": {"symbol": "ADANIPORTS", "token": "15083", "exchange": "NSE"},
        "kotakneo": {"symbol": "ADANIPORTS", "token": "15083", "exchange": "NSE"},
        "tradejini": {"symbol": "ADANIPORTS-EQ", "token": "15083", "exchange": "NSE"},
        "zebu": {"symbol": "ADANIPORTS-EQ", "token": "15083", "exchange": "NSE"},
        "enrichmoney": {"symbol": "ADANIPORTS-EQ", "token": "15083", "exchange": "NSE"},
    },
    "APOLLOHOSP": {
        "zerodha": {"trading_symbol": "APOLLOHOSP", "exchange": "NSE", "token": "157"},
        "aliceblue": {"trading_symbol": "APOLLOHOSP-EQ", "symbol_id": "157", "exch": "NSE"},
        "fyers": {"symbol": "NSE:APOLLOHOSP-EQ", "token": "157"},
        "finvasia": {"symbol": "APOLLOHOSP-EQ", "token": "157", "exchange": "NSE"},
        "dhan": {"security_id": "157", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "APOLLOHOSP-EQ", "token": "157", "exchange": "NSE"},
        "acagarwal": {"symbol": "APOLLOHOSP-EQ", "token": "157", "exchange": "NSE"},
        "motilaloswal": {"symbol": "APOLLOHOSP", "token": "157", "exchange": "NSE"},
        "kotakneo": {"symbol": "APOLLOHOSP", "token": "157", "exchange": "NSE"},
        "tradejini": {"symbol": "APOLLOHOSP-EQ", "token": "157", "exchange": "NSE"},
        "zebu": {"symbol": "APOLLOHOSP-EQ", "token": "157", "exchange": "NSE"},
        "enrichmoney": {"symbol": "APOLLOHOSP-EQ", "token": "157", "exchange": "NSE"},
    },
    "ASIANPAINT": {
        "zerodha": {"trading_symbol": "ASIANPAINT", "exchange": "NSE", "token": "6049"},
        "aliceblue": {"trading_symbol": "ASIANPAINT-EQ", "symbol_id": "6049", "exch": "NSE"},
        "fyers": {"symbol": "NSE:ASIANPAINT-EQ", "token": "6049"},
        "finvasia": {"symbol": "ASIANPAINT-EQ", "token": "6049", "exchange": "NSE"},
        "dhan": {"security_id": "6049", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "ASIANPAINT-EQ", "token": "6049", "exchange": "NSE"},
        "acagarwal": {"symbol": "ASIANPAINT-EQ", "token": "6049", "exchange": "NSE"},
        "motilaloswal": {"symbol": "ASIANPAINT", "token": "6049", "exchange": "NSE"},
        "kotakneo": {"symbol": "ASIANPAINT", "token": "6049", "exchange": "NSE"},
        "tradejini": {"symbol": "ASIANPAINT-EQ", "token": "6049", "exchange": "NSE"},
        "zebu": {"symbol": "ASIANPAINT-EQ", "token": "6049", "exchange": "NSE"},
        "enrichmoney": {"symbol": "ASIANPAINT-EQ", "token": "6049", "exchange": "NSE"},
    },
    "AXISBANK": {
        "zerodha": {"trading_symbol": "AXISBANK", "exchange": "NSE", "token": "1512"},
        "aliceblue": {"trading_symbol": "AXISBANK-EQ", "symbol_id": "1512", "exch": "NSE"},
        "fyers": {"symbol": "NSE:AXISBANK-EQ", "token": "1512"},
        "finvasia": {"symbol": "AXISBANK-EQ", "token": "1512", "exchange": "NSE"},
        "dhan": {"security_id": "1512", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "AXISBANK-EQ", "token": "1512", "exchange": "NSE"},
        "acagarwal": {"symbol": "AXISBANK-EQ", "token": "1512", "exchange": "NSE"},
        "motilaloswal": {"symbol": "AXISBANK", "token": "1512", "exchange": "NSE"},
        "kotakneo": {"symbol": "AXISBANK", "token": "1512", "exchange": "NSE"},
        "tradejini": {"symbol": "AXISBANK-EQ", "token": "1512", "exchange": "NSE"},
        "zebu": {"symbol": "AXISBANK-EQ", "token": "1512", "exchange": "NSE"},
        "enrichmoney": {"symbol": "AXISBANK-EQ", "token": "1512", "exchange": "NSE"},
    },
    "BAJAJ-AUTO": {
        "zerodha": {"trading_symbol": "BAJAJ-AUTO", "exchange": "NSE", "token": "426"},
        "aliceblue": {"trading_symbol": "BAJAJ-AUTO-EQ", "symbol_id": "426", "exch": "NSE"},
        "fyers": {"symbol": "NSE:BAJAJ-AUTO-EQ", "token": "426"},
        "finvasia": {"symbol": "BAJAJ-AUTO-EQ", "token": "426", "exchange": "NSE"},
        "dhan": {"security_id": "426", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "BAJAJ-AUTO-EQ", "token": "426", "exchange": "NSE"},
        "acagarwal": {"symbol": "BAJAJ-AUTO-EQ", "token": "426", "exchange": "NSE"},
        "motilaloswal": {"symbol": "BAJAJ-AUTO", "token": "426", "exchange": "NSE"},
        "kotakneo": {"symbol": "BAJAJ-AUTO", "token": "426", "exchange": "NSE"},
        "tradejini": {"symbol": "BAJAJ-AUTO-EQ", "token": "426", "exchange": "NSE"},
        "zebu": {"symbol": "BAJAJ-AUTO-EQ", "token": "426", "exchange": "NSE"},
        "enrichmoney": {"symbol": "BAJAJ-AUTO-EQ", "token": "426", "exchange": "NSE"},
    },
    "BAJFINANCE": {
        "zerodha": {"trading_symbol": "BAJFINANCE", "exchange": "NSE", "token": "317"},
        "aliceblue": {"trading_symbol": "BAJFINANCE-EQ", "symbol_id": "317", "exch": "NSE"},
        "fyers": {"symbol": "NSE:BAJFINANCE-EQ", "token": "317"},
        "finvasia": {"symbol": "BAJFINANCE-EQ", "token": "317", "exchange": "NSE"},
        "dhan": {"security_id": "317", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "BAJFINANCE-EQ", "token": "317", "exchange": "NSE"},
        "acagarwal": {"symbol": "BAJFINANCE-EQ", "token": "317", "exchange": "NSE"},
        "motilaloswal": {"symbol": "BAJFINANCE", "token": "317", "exchange": "NSE"},
        "kotakneo": {"symbol": "BAJFINANCE", "token": "317", "exchange": "NSE"},
        "tradejini": {"symbol": "BAJFINANCE-EQ", "token": "317", "exchange": "NSE"},
        "zebu": {"symbol": "BAJFINANCE-EQ", "token": "317", "exchange": "NSE"},
        "enrichmoney": {"symbol": "BAJFINANCE-EQ", "token": "317", "exchange": "NSE"},
    },
    "BAJAJFINSV": {
        "zerodha": {"trading_symbol": "BAJAJFINSV", "exchange": "NSE", "token": "952747"},
        "aliceblue": {"trading_symbol": "BAJAJFINSV-EQ", "symbol_id": "952747", "exch": "NSE"},
        "fyers": {"symbol": "NSE:BAJAJFINSV-EQ", "token": "952747"},
        "finvasia": {"symbol": "BAJAJFINSV-EQ", "token": "952747", "exchange": "NSE"},
        "dhan": {"security_id": "952747", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "BAJAJFINSV-EQ", "token": "952747", "exchange": "NSE"},
        "acagarwal": {"symbol": "BAJAJFINSV-EQ", "token": "952747", "exchange": "NSE"},
        "motilaloswal": {"symbol": "BAJAJFINSV", "token": "952747", "exchange": "NSE"},
        "kotakneo": {"symbol": "BAJAJFINSV", "token": "952747", "exchange": "NSE"},
        "tradejini": {"symbol": "BAJAJFINSV-EQ", "token": "952747", "exchange": "NSE"},
        "zebu": {"symbol": "BAJAJFINSV-EQ", "token": "952747", "exchange": "NSE"},
        "enrichmoney": {"symbol": "BAJAJFINSV-EQ", "token": "952747", "exchange": "NSE"},
    },
    "BPCL": {
        "zerodha": {"trading_symbol": "BPCL", "exchange": "NSE", "token": "526"},
        "aliceblue": {"trading_symbol": "BPCL-EQ", "symbol_id": "526", "exch": "NSE"},
        "fyers": {"symbol": "NSE:BPCL-EQ", "token": "526"},
        "finvasia": {"symbol": "BPCL-EQ", "token": "526", "exchange": "NSE"},
        "dhan": {"security_id": "526", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "BPCL-EQ", "token": "526", "exchange": "NSE"},
        "acagarwal": {"symbol": "BPCL-EQ", "token": "526", "exchange": "NSE"},
        "motilaloswal": {"symbol": "BPCL", "token": "526", "exchange": "NSE"},
        "kotakneo": {"symbol": "BPCL", "token": "526", "exchange": "NSE"},
        "tradejini": {"symbol": "BPCL-EQ", "token": "526", "exchange": "NSE"},
        "zebu": {"symbol": "BPCL-EQ", "token": "526", "exchange": "NSE"},
        "enrichmoney": {"symbol": "BPCL-EQ", "token": "526", "exchange": "NSE"},
    },
    "BRITANNIA": {
        "zerodha": {"trading_symbol": "BRITANNIA", "exchange": "NSE", "token": "5477"},
        "aliceblue": {"trading_symbol": "BRITANNIA-EQ", "symbol_id": "5477", "exch": "NSE"},
        "fyers": {"symbol": "NSE:BRITANNIA-EQ", "token": "5477"},
        "finvasia": {"symbol": "BRITANNIA-EQ", "token": "5477", "exchange": "NSE"},
        "dhan": {"security_id": "5477", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "BRITANNIA-EQ", "token": "5477", "exchange": "NSE"},
        "acagarwal": {"symbol": "BRITANNIA-EQ", "token": "5477", "exchange": "NSE"},
        "motilaloswal": {"symbol": "BRITANNIA", "token": "5477", "exchange": "NSE"},
        "kotakneo": {"symbol": "BRITANNIA", "token": "5477", "exchange": "NSE"},
        "tradejini": {"symbol": "BRITANNIA-EQ", "token": "5477", "exchange": "NSE"},
        "zebu": {"symbol": "BRITANNIA-EQ", "token": "5477", "exchange": "NSE"},
        "enrichmoney": {"symbol": "BRITANNIA-EQ", "token": "5477", "exchange": "NSE"},
    },
    "CIPLA": {
        "zerodha": {"trading_symbol": "CIPLA", "exchange": "NSE", "token": "694"},
        "aliceblue": {"trading_symbol": "CIPLA-EQ", "symbol_id": "694", "exch": "NSE"},
        "fyers": {"symbol": "NSE:CIPLA-EQ", "token": "694"},
        "finvasia": {"symbol": "CIPLA-EQ", "token": "694", "exchange": "NSE"},
        "dhan": {"security_id": "694", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "CIPLA-EQ", "token": "694", "exchange": "NSE"},
        "acagarwal": {"symbol": "CIPLA-EQ", "token": "694", "exchange": "NSE"},
        "motilaloswal": {"symbol": "CIPLA", "token": "694", "exchange": "NSE"},
        "kotakneo": {"symbol": "CIPLA", "token": "694", "exchange": "NSE"},
        "tradejini": {"symbol": "CIPLA-EQ", "token": "694", "exchange": "NSE"},
        "zebu": {"symbol": "CIPLA-EQ", "token": "694", "exchange": "NSE"},
        "enrichmoney": {"symbol": "CIPLA-EQ", "token": "694", "exchange": "NSE"},
    },

    "COALINDIA": {
        "zerodha": {"trading_symbol": "COALINDIA", "exchange": "NSE", "token": "5214"},
        "aliceblue": {"trading_symbol": "COALINDIA-EQ", "symbol_id": "5214", "exch": "NSE"},
        "fyers": {"symbol": "NSE:COALINDIA-EQ", "token": "5214"},
        "finvasia": {"symbol": "COALINDIA-EQ", "token": "5214", "exchange": "NSE"},
        "dhan": {"security_id": "5214", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "COALINDIA-EQ", "token": "5214", "exchange": "NSE"},
        "acagarwal": {"symbol": "COALINDIA-EQ", "token": "5214", "exchange": "NSE"},
        "motilaloswal": {"symbol": "COALINDIA", "token": "5214", "exchange": "NSE"},
        "kotakneo": {"symbol": "COALINDIA", "token": "5214", "exchange": "NSE"},
        "tradejini": {"symbol": "COALINDIA-EQ", "token": "5214", "exchange": "NSE"},
        "zebu": {"symbol": "COALINDIA-EQ", "token": "5214", "exchange": "NSE"},
        "enrichmoney": {"symbol": "COALINDIA-EQ", "token": "5214", "exchange": "NSE"},
    },
    "DIVISLAB": {
        "zerodha": {"trading_symbol": "DIVISLAB", "exchange": "NSE", "token": "2803"},
        "aliceblue": {"trading_symbol": "DIVISLAB-EQ", "symbol_id": "2803", "exch": "NSE"},
        "fyers": {"symbol": "NSE:DIVISLAB-EQ", "token": "2803"},
        "finvasia": {"symbol": "DIVISLAB-EQ", "token": "2803", "exchange": "NSE"},
        "dhan": {"security_id": "2803", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "DIVISLAB-EQ", "token": "2803", "exchange": "NSE"},
        "acagarwal": {"symbol": "DIVISLAB-EQ", "token": "2803", "exchange": "NSE"},
        "motilaloswal": {"symbol": "DIVISLAB", "token": "2803", "exchange": "NSE"},
        "kotakneo": {"symbol": "DIVISLAB", "token": "2803", "exchange": "NSE"},
        "tradejini": {"symbol": "DIVISLAB-EQ", "token": "2803", "exchange": "NSE"},
        "zebu": {"symbol": "DIVISLAB-EQ", "token": "2803", "exchange": "NSE"},
        "enrichmoney": {"symbol": "DIVISLAB-EQ", "token": "2803", "exchange": "NSE"},
    },
    "DRREDDY": {
        "zerodha": {"trading_symbol": "DRREDDY", "exchange": "NSE", "token": "2252"},
        "aliceblue": {"trading_symbol": "DRREDDY-EQ", "symbol_id": "2252", "exch": "NSE"},
        "fyers": {"symbol": "NSE:DRREDDY-EQ", "token": "2252"},
        "finvasia": {"symbol": "DRREDDY-EQ", "token": "2252", "exchange": "NSE"},
        "dhan": {"security_id": "2252", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "DRREDDY-EQ", "token": "2252", "exchange": "NSE"},
        "acagarwal": {"symbol": "DRREDDY-EQ", "token": "2252", "exchange": "NSE"},
        "motilaloswal": {"symbol": "DRREDDY", "token": "2252", "exchange": "NSE"},
        "kotakneo": {"symbol": "DRREDDY", "token": "2252", "exchange": "NSE"},
        "tradejini": {"symbol": "DRREDDY-EQ", "token": "2252", "exchange": "NSE"},
        "zebu": {"symbol": "DRREDDY-EQ", "token": "2252", "exchange": "NSE"},
        "enrichmoney": {"symbol": "DRREDDY-EQ", "token": "2252", "exchange": "NSE"},
    },
    "EICHERMOT": {
        "zerodha": {"trading_symbol": "EICHERMOT", "exchange": "NSE", "token": "910"},
        "aliceblue": {"trading_symbol": "EICHERMOT-EQ", "symbol_id": "910", "exch": "NSE"},
        "fyers": {"symbol": "NSE:EICHERMOT-EQ", "token": "910"},
        "finvasia": {"symbol": "EICHERMOT-EQ", "token": "910", "exchange": "NSE"},
        "dhan": {"security_id": "910", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "EICHERMOT-EQ", "token": "910", "exchange": "NSE"},
        "acagarwal": {"symbol": "EICHERMOT-EQ", "token": "910", "exchange": "NSE"},
        "motilaloswal": {"symbol": "EICHERMOT", "token": "910", "exchange": "NSE"},
        "kotakneo": {"symbol": "EICHERMOT", "token": "910", "exchange": "NSE"},
        "tradejini": {"symbol": "EICHERMOT-EQ", "token": "910", "exchange": "NSE"},
        "zebu": {"symbol": "EICHERMOT-EQ", "token": "910", "exchange": "NSE"},
        "enrichmoney": {"symbol": "EICHERMOT-EQ", "token": "910", "exchange": "NSE"},
    },
    "GRASIM": {
        "zerodha": {"trading_symbol": "GRASIM", "exchange": "NSE", "token": "1232"},
        "aliceblue": {"trading_symbol": "GRASIM-EQ", "symbol_id": "1232", "exch": "NSE"},
        "fyers": {"symbol": "NSE:GRASIM-EQ", "token": "1232"},
        "finvasia": {"symbol": "GRASIM-EQ", "token": "1232", "exchange": "NSE"},
        "dhan": {"security_id": "1232", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "GRASIM-EQ", "token": "1232", "exchange": "NSE"},
        "acagarwal": {"symbol": "GRASIM-EQ", "token": "1232", "exchange": "NSE"},
        "motilaloswal": {"symbol": "GRASIM", "token": "1232", "exchange": "NSE"},
        "kotakneo": {"symbol": "GRASIM", "token": "1232", "exchange": "NSE"},
        "tradejini": {"symbol": "GRASIM-EQ", "token": "1232", "exchange": "NSE"},
        "zebu": {"symbol": "GRASIM-EQ", "token": "1232", "exchange": "NSE"},
        "enrichmoney": {"symbol": "GRASIM-EQ", "token": "1232", "exchange": "NSE"},
    },
    "HCLTECH": {
        "zerodha": {"trading_symbol": "HCLTECH", "exchange": "NSE", "token": "7229"},
        "aliceblue": {"trading_symbol": "HCLTECH-EQ", "symbol_id": "7229", "exch": "NSE"},
        "fyers": {"symbol": "NSE:HCLTECH-EQ", "token": "7229"},
        "finvasia": {"symbol": "HCLTECH-EQ", "token": "7229", "exchange": "NSE"},
        "dhan": {"security_id": "7229", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "HCLTECH-EQ", "token": "7229", "exchange": "NSE"},
        "acagarwal": {"symbol": "HCLTECH-EQ", "token": "7229", "exchange": "NSE"},
        "motilaloswal": {"symbol": "HCLTECH", "token": "7229", "exchange": "NSE"},
        "kotakneo": {"symbol": "HCLTECH", "token": "7229", "exchange": "NSE"},
        "tradejini": {"symbol": "HCLTECH-EQ", "token": "7229", "exchange": "NSE"},
        "zebu": {"symbol": "HCLTECH-EQ", "token": "7229", "exchange": "NSE"},
        "enrichmoney": {"symbol": "HCLTECH-EQ", "token": "7229", "exchange": "NSE"},
    },
    "HEROMOTOCO": {
        "zerodha": {"trading_symbol": "HEROMOTOCO", "exchange": "NSE", "token": "1348"},
        "aliceblue": {"trading_symbol": "HEROMOTOCO-EQ", "symbol_id": "1348", "exch": "NSE"},
        "fyers": {"symbol": "NSE:HEROMOTOCO-EQ", "token": "1348"},
        "finvasia": {"symbol": "HEROMOTOCO-EQ", "token": "1348", "exchange": "NSE"},
        "dhan": {"security_id": "1348", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "HEROMOTOCO-EQ", "token": "1348", "exchange": "NSE"},
        "acagarwal": {"symbol": "HEROMOTOCO-EQ", "token": "1348", "exchange": "NSE"},
        "motilaloswal": {"symbol": "HEROMOTOCO", "token": "1348", "exchange": "NSE"},
        "kotakneo": {"symbol": "HEROMOTOCO", "token": "1348", "exchange": "NSE"},
        "tradejini": {"symbol": "HEROMOTOCO-EQ", "token": "1348", "exchange": "NSE"},
        "zebu": {"symbol": "HEROMOTOCO-EQ", "token": "1348", "exchange": "NSE"},
        "enrichmoney": {"symbol": "HEROMOTOCO-EQ", "token": "1348", "exchange": "NSE"},
    },
    "HINDALCO": {
        "zerodha": {"trading_symbol": "HINDALCO", "exchange": "NSE", "token": "1363"},
        "aliceblue": {"trading_symbol": "HINDALCO-EQ", "symbol_id": "1363", "exch": "NSE"},
        "fyers": {"symbol": "NSE:HINDALCO-EQ", "token": "1363"},
        "finvasia": {"symbol": "HINDALCO-EQ", "token": "1363", "exchange": "NSE"},
        "dhan": {"security_id": "1363", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "HINDALCO-EQ", "token": "1363", "exchange": "NSE"},
        "acagarwal": {"symbol": "HINDALCO-EQ", "token": "1363", "exchange": "NSE"},
        "motilaloswal": {"symbol": "HINDALCO", "token": "1363", "exchange": "NSE"},
        "kotakneo": {"symbol": "HINDALCO", "token": "1363", "exchange": "NSE"},
        "tradejini": {"symbol": "HINDALCO-EQ", "token": "1363", "exchange": "NSE"},
        "zebu": {"symbol": "HINDALCO-EQ", "token": "1363", "exchange": "NSE"},
        "enrichmoney": {"symbol": "HINDALCO-EQ", "token": "1363", "exchange": "NSE"},
    },
    "HINDUNILVR": {
        "zerodha": {"trading_symbol": "HINDUNILVR", "exchange": "NSE", "token": "1394"},
        "aliceblue": {"trading_symbol": "HINDUNILVR-EQ", "symbol_id": "1394", "exch": "NSE"},
        "fyers": {"symbol": "NSE:HINDUNILVR-EQ", "token": "1394"},
        "finvasia": {"symbol": "HINDUNILVR-EQ", "token": "1394", "exchange": "NSE"},
        "dhan": {"security_id": "1394", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "HINDUNILVR-EQ", "token": "1394", "exchange": "NSE"},
        "acagarwal": {"symbol": "HINDUNILVR-EQ", "token": "1394", "exchange": "NSE"},
        "motilaloswal": {"symbol": "HINDUNILVR", "token": "1394", "exchange": "NSE"},
        "kotakneo": {"symbol": "HINDUNILVR", "token": "1394", "exchange": "NSE"},
        "tradejini": {"symbol": "HINDUNILVR-EQ", "token": "1394", "exchange": "NSE"},
        "zebu": {"symbol": "HINDUNILVR-EQ", "token": "1394", "exchange": "NSE"},
        "enrichmoney": {"symbol": "HINDUNILVR-EQ", "token": "1394", "exchange": "NSE"},
    },

    "ICICIBANK": {
        "zerodha": {"trading_symbol": "ICICIBANK", "exchange": "NSE", "token": "4963"},
        "aliceblue": {"trading_symbol": "ICICIBANK-EQ", "symbol_id": "4963", "exch": "NSE"},
        "fyers": {"symbol": "NSE:ICICIBANK-EQ", "token": "4963"},
        "finvasia": {"symbol": "ICICIBANK-EQ", "token": "4963", "exchange": "NSE"},
        "dhan": {"security_id": "4963", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "ICICIBANK-EQ", "token": "4963", "exchange": "NSE"},
        "acagarwal": {"symbol": "ICICIBANK-EQ", "token": "4963", "exchange": "NSE"},
        "motilaloswal": {"symbol": "ICICIBANK", "token": "4963", "exchange": "NSE"},
        "kotakneo": {"symbol": "ICICIBANK", "token": "4963", "exchange": "NSE"},
        "tradejini": {"symbol": "ICICIBANK-EQ", "token": "4963", "exchange": "NSE"},
        "zebu": {"symbol": "ICICIBANK-EQ", "token": "4963", "exchange": "NSE"},
        "enrichmoney": {"symbol": "ICICIBANK-EQ", "token": "4963", "exchange": "NSE"},
    },
    "INDUSINDBK": {
        "zerodha": {"trading_symbol": "INDUSINDBK", "exchange": "NSE", "token": "5258"},
        "aliceblue": {"trading_symbol": "INDUSINDBK-EQ", "symbol_id": "5258", "exch": "NSE"},
        "fyers": {"symbol": "NSE:INDUSINDBK-EQ", "token": "5258"},
        "finvasia": {"symbol": "INDUSINDBK-EQ", "token": "5258", "exchange": "NSE"},
        "dhan": {"security_id": "5258", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "INDUSINDBK-EQ", "token": "5258", "exchange": "NSE"},
        "acagarwal": {"symbol": "INDUSINDBK-EQ", "token": "5258", "exchange": "NSE"},
        "motilaloswal": {"symbol": "INDUSINDBK", "token": "5258", "exchange": "NSE"},
        "kotakneo": {"symbol": "INDUSINDBK", "token": "5258", "exchange": "NSE"},
        "tradejini": {"symbol": "INDUSINDBK-EQ", "token": "5258", "exchange": "NSE"},
        "zebu": {"symbol": "INDUSINDBK-EQ", "token": "5258", "exchange": "NSE"},
        "enrichmoney": {"symbol": "INDUSINDBK-EQ", "token": "5258", "exchange": "NSE"},
    },
    "INFY": {
        "zerodha": {"trading_symbol": "INFY", "exchange": "NSE", "token": "10999"},
        "aliceblue": {"trading_symbol": "INFY-EQ", "symbol_id": "10999", "exch": "NSE"},
        "fyers": {"symbol": "NSE:INFY-EQ", "token": "10999"},
        "finvasia": {"symbol": "INFY-EQ", "token": "10999", "exchange": "NSE"},
        "dhan": {"security_id": "10999", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "INFY-EQ", "token": "10999", "exchange": "NSE"},
        "acagarwal": {"symbol": "INFY-EQ", "token": "10999", "exchange": "NSE"},
        "motilaloswal": {"symbol": "INFY", "token": "10999", "exchange": "NSE"},
        "kotakneo": {"symbol": "INFY", "token": "10999", "exchange": "NSE"},
        "tradejini": {"symbol": "INFY-EQ", "token": "10999", "exchange": "NSE"},
        "zebu": {"symbol": "INFY-EQ", "token": "10999", "exchange": "NSE"},
        "enrichmoney": {"symbol": "INFY-EQ", "token": "10999", "exchange": "NSE"},
    },
    "ITC": {
        "zerodha": {"trading_symbol": "ITC", "exchange": "NSE", "token": "1660"},
        "aliceblue": {"trading_symbol": "ITC-EQ", "symbol_id": "1660", "exch": "NSE"},
        "fyers": {"symbol": "NSE:ITC-EQ", "token": "1660"},
        "finvasia": {"symbol": "ITC-EQ", "token": "1660", "exchange": "NSE"},
        "dhan": {"security_id": "1660", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "ITC-EQ", "token": "1660", "exchange": "NSE"},
        "acagarwal": {"symbol": "ITC-EQ", "token": "1660", "exchange": "NSE"},
        "motilaloswal": {"symbol": "ITC", "token": "1660", "exchange": "NSE"},
        "kotakneo": {"symbol": "ITC", "token": "1660", "exchange": "NSE"},
        "tradejini": {"symbol": "ITC-EQ", "token": "1660", "exchange": "NSE"},
        "zebu": {"symbol": "ITC-EQ", "token": "1660", "exchange": "NSE"},
        "enrichmoney": {"symbol": "ITC-EQ", "token": "1660", "exchange": "NSE"},
    },
    "JSWSTEEL": {
        "zerodha": {"trading_symbol": "JSWSTEEL", "exchange": "NSE", "token": "11723"},
        "aliceblue": {"trading_symbol": "JSWSTEEL-EQ", "symbol_id": "11723", "exch": "NSE"},
        "fyers": {"symbol": "NSE:JSWSTEEL-EQ", "token": "11723"},
        "finvasia": {"symbol": "JSWSTEEL-EQ", "token": "11723", "exchange": "NSE"},
        "dhan": {"security_id": "11723", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "JSWSTEEL-EQ", "token": "11723", "exchange": "NSE"},
        "acagarwal": {"symbol": "JSWSTEEL-EQ", "token": "11723", "exchange": "NSE"},
        "motilaloswal": {"symbol": "JSWSTEEL", "token": "11723", "exchange": "NSE"},
        "kotakneo": {"symbol": "JSWSTEEL", "token": "11723", "exchange": "NSE"},
        "tradejini": {"symbol": "JSWSTEEL-EQ", "token": "11723", "exchange": "NSE"},
        "zebu": {"symbol": "JSWSTEEL-EQ", "token": "11723", "exchange": "NSE"},
        "enrichmoney": {"symbol": "JSWSTEEL-EQ", "token": "11723", "exchange": "NSE"},
    },
    "KOTAKBANK": {
        "zerodha": {"trading_symbol": "KOTAKBANK", "exchange": "NSE", "token": "1922"},
        "aliceblue": {"trading_symbol": "KOTAKBANK-EQ", "symbol_id": "1922", "exch": "NSE"},
        "fyers": {"symbol": "NSE:KOTAKBANK-EQ", "token": "1922"},
        "finvasia": {"symbol": "KOTAKBANK-EQ", "token": "1922", "exchange": "NSE"},
        "dhan": {"security_id": "1922", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "KOTAKBANK-EQ", "token": "1922", "exchange": "NSE"},
        "acagarwal": {"symbol": "KOTAKBANK-EQ", "token": "1922", "exchange": "NSE"},
        "motilaloswal": {"symbol": "KOTAKBANK", "token": "1922", "exchange": "NSE"},
        "kotakneo": {"symbol": "KOTAKBANK", "token": "1922", "exchange": "NSE"},
        "tradejini": {"symbol": "KOTAKBANK-EQ", "token": "1922", "exchange": "NSE"},
        "zebu": {"symbol": "KOTAKBANK-EQ", "token": "1922", "exchange": "NSE"},
        "enrichmoney": {"symbol": "KOTAKBANK-EQ", "token": "1922", "exchange": "NSE"},
    },
    "LT": {
        "zerodha": {"trading_symbol": "LT", "exchange": "NSE", "token": "2931"},
        "aliceblue": {"trading_symbol": "LT-EQ", "symbol_id": "2931", "exch": "NSE"},
        "fyers": {"symbol": "NSE:LT-EQ", "token": "2931"},
        "finvasia": {"symbol": "LT-EQ", "token": "2931", "exchange": "NSE"},
        "dhan": {"security_id": "2931", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "LT-EQ", "token": "2931", "exchange": "NSE"},
        "acagarwal": {"symbol": "LT-EQ", "token": "2931", "exchange": "NSE"},
        "motilaloswal": {"symbol": "LT", "token": "2931", "exchange": "NSE"},
        "kotakneo": {"symbol": "LT", "token": "2931", "exchange": "NSE"},
        "tradejini": {"symbol": "LT-EQ", "token": "2931", "exchange": "NSE"},
        "zebu": {"symbol": "LT-EQ", "token": "2931", "exchange": "NSE"},
        "enrichmoney": {"symbol": "LT-EQ", "token": "2931", "exchange": "NSE"},
    },
    "M&M": {
        "zerodha": {"trading_symbol": "M&M", "exchange": "NSE", "token": "2031"},
        "aliceblue": {"trading_symbol": "M&M-EQ", "symbol_id": "2031", "exch": "NSE"},
        "fyers": {"symbol": "NSE:M&M-EQ", "token": "2031"},
        "finvasia": {"symbol": "M&M-EQ", "token": "2031", "exchange": "NSE"},
        "dhan": {"security_id": "2031", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "M&M-EQ", "token": "2031", "exchange": "NSE"},
        "acagarwal": {"symbol": "M&M-EQ", "token": "2031", "exchange": "NSE"},
        "motilaloswal": {"symbol": "M&M", "token": "2031", "exchange": "NSE"},
        "kotakneo": {"symbol": "M&M", "token": "2031", "exchange": "NSE"},
        "tradejini": {"symbol": "M&M-EQ", "token": "2031", "exchange": "NSE"},
        "zebu": {"symbol": "M&M-EQ", "token": "2031", "exchange": "NSE"},
        "enrichmoney": {"symbol": "M&M-EQ", "token": "2031", "exchange": "NSE"},
    },
    "MARUTI": {
        "zerodha": {"trading_symbol": "MARUTI", "exchange": "NSE", "token": "2671"},
        "aliceblue": {"trading_symbol": "MARUTI-EQ", "symbol_id": "2671", "exch": "NSE"},
        "fyers": {"symbol": "NSE:MARUTI-EQ", "token": "2671"},
        "finvasia": {"symbol": "MARUTI-EQ", "token": "2671", "exchange": "NSE"},
        "dhan": {"security_id": "2671", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "MARUTI-EQ", "token": "2671", "exchange": "NSE"},
        "acagarwal": {"symbol": "MARUTI-EQ", "token": "2671", "exchange": "NSE"},
        "motilaloswal": {"symbol": "MARUTI", "token": "2671", "exchange": "NSE"},
        "kotakneo": {"symbol": "MARUTI", "token": "2671", "exchange": "NSE"},
        "tradejini": {"symbol": "MARUTI-EQ", "token": "2671", "exchange": "NSE"},
        "zebu": {"symbol": "MARUTI-EQ", "token": "2671", "exchange": "NSE"},
        "enrichmoney": {"symbol": "MARUTI-EQ", "token": "2671", "exchange": "NSE"},
    },
    "NESTLEIND": {
        "zerodha": {"trading_symbol": "NESTLEIND", "exchange": "NSE", "token": "17963"},
        "aliceblue": {"trading_symbol": "NESTLEIND-EQ", "symbol_id": "17963", "exch": "NSE"},
        "fyers": {"symbol": "NSE:NESTLEIND-EQ", "token": "17963"},
        "finvasia": {"symbol": "NESTLEIND-EQ", "token": "17963", "exchange": "NSE"},
        "dhan": {"security_id": "17963", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "NESTLEIND-EQ", "token": "17963", "exchange": "NSE"},
        "acagarwal": {"symbol": "NESTLEIND-EQ", "token": "17963", "exchange": "NSE"},
        "motilaloswal": {"symbol": "NESTLEIND", "token": "17963", "exchange": "NSE"},
        "kotakneo": {"symbol": "NESTLEIND", "token": "17963", "exchange": "NSE"},
        "tradejini": {"symbol": "NESTLEIND-EQ", "token": "17963", "exchange": "NSE"},
        "zebu": {"symbol": "NESTLEIND-EQ", "token": "17963", "exchange": "NSE"},
        "enrichmoney": {"symbol": "NESTLEIND-EQ", "token": "17963", "exchange": "NSE"},
    },
    "NTPC": {
        "zerodha": {"trading_symbol": "NTPC", "exchange": "NSE", "token": "2972"},
        "aliceblue": {"trading_symbol": "NTPC-EQ", "symbol_id": "2972", "exch": "NSE"},
        "fyers": {"symbol": "NSE:NTPC-EQ", "token": "2972"},
        "finvasia": {"symbol": "NTPC-EQ", "token": "2972", "exchange": "NSE"},
        "dhan": {"security_id": "2972", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "NTPC-EQ", "token": "2972", "exchange": "NSE"},
        "acagarwal": {"symbol": "NTPC-EQ", "token": "2972", "exchange": "NSE"},
        "motilaloswal": {"symbol": "NTPC", "token": "2972", "exchange": "NSE"},
        "kotakneo": {"symbol": "NTPC", "token": "2972", "exchange": "NSE"},
        "tradejini": {"symbol": "NTPC-EQ", "token": "2972", "exchange": "NSE"},
        "zebu": {"symbol": "NTPC-EQ", "token": "2972", "exchange": "NSE"},
        "enrichmoney": {"symbol": "NTPC-EQ", "token": "2972", "exchange": "NSE"},
    },
    "ONGC": {
        "zerodha": {"trading_symbol": "ONGC", "exchange": "NSE", "token": "2475"},
        "aliceblue": {"trading_symbol": "ONGC-EQ", "symbol_id": "2475", "exch": "NSE"},
        "fyers": {"symbol": "NSE:ONGC-EQ", "token": "2475"},
        "finvasia": {"symbol": "ONGC-EQ", "token": "2475", "exchange": "NSE"},
        "dhan": {"security_id": "2475", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "ONGC-EQ", "token": "2475", "exchange": "NSE"},
        "acagarwal": {"symbol": "ONGC-EQ", "token": "2475", "exchange": "NSE"},
        "motilaloswal": {"symbol": "ONGC", "token": "2475", "exchange": "NSE"},
        "kotakneo": {"symbol": "ONGC", "token": "2475", "exchange": "NSE"},
        "tradejini": {"symbol": "ONGC-EQ", "token": "2475", "exchange": "NSE"},
        "zebu": {"symbol": "ONGC-EQ", "token": "2475", "exchange": "NSE"},
        "enrichmoney": {"symbol": "ONGC-EQ", "token": "2475", "exchange": "NSE"},
    },
    "POWERGRID": {
        "zerodha": {"trading_symbol": "POWERGRID", "exchange": "NSE", "token": "14977"},
        "aliceblue": {"trading_symbol": "POWERGRID-EQ", "symbol_id": "14977", "exch": "NSE"},
        "fyers": {"symbol": "NSE:POWERGRID-EQ", "token": "14977"},
        "finvasia": {"symbol": "POWERGRID-EQ", "token": "14977", "exchange": "NSE"},
        "dhan": {"security_id": "14977", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "POWERGRID-EQ", "token": "14977", "exchange": "NSE"},
        "acagarwal": {"symbol": "POWERGRID-EQ", "token": "14977", "exchange": "NSE"},
        "motilaloswal": {"symbol": "POWERGRID", "token": "14977", "exchange": "NSE"},
        "kotakneo": {"symbol": "POWERGRID", "token": "14977", "exchange": "NSE"},
        "tradejini": {"symbol": "POWERGRID-EQ", "token": "14977", "exchange": "NSE"},
        "zebu": {"symbol": "POWERGRID-EQ", "token": "14977", "exchange": "NSE"},
        "enrichmoney": {"symbol": "POWERGRID-EQ", "token": "14977", "exchange": "NSE"},
    },
    "RELIANCE": {
        "zerodha": {"trading_symbol": "RELIANCE", "exchange": "NSE", "token": "2885"},
        "aliceblue": {"trading_symbol": "RELIANCE-EQ", "symbol_id": "2885", "exch": "NSE"},
        "fyers": {"symbol": "NSE:RELIANCE-EQ", "token": "2885"},
        "finvasia": {"symbol": "RELIANCE-EQ", "token": "2885", "exchange": "NSE"},
        "dhan": {"security_id": "2885", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "RELIANCE-EQ", "token": "2885", "exchange": "NSE"},
        "acagarwal": {"symbol": "RELIANCE-EQ", "token": "2885", "exchange": "NSE"},
        "motilaloswal": {"symbol": "RELIANCE", "token": "2885", "exchange": "NSE"},
        "kotakneo": {"symbol": "RELIANCE", "token": "2885", "exchange": "NSE"},
        "tradejini": {"symbol": "RELIANCE-EQ", "token": "2885", "exchange": "NSE"},
        "zebu": {"symbol": "RELIANCE-EQ", "token": "2885", "exchange": "NSE"},
        "enrichmoney": {"symbol": "RELIANCE-EQ", "token": "2885", "exchange": "NSE"},
    },
    "SBIN": {
        "zerodha": {"trading_symbol": "SBIN", "exchange": "NSE", "token": "3045"},
        "aliceblue": {"trading_symbol": "SBIN-EQ", "symbol_id": "3045", "exch": "NSE"},
        "fyers": {"symbol": "NSE:SBIN-EQ", "token": "3045"},
        "finvasia": {"symbol": "SBIN-EQ", "token": "3045", "exchange": "NSE"},
        "dhan": {"security_id": "3045", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "SBIN-EQ", "token": "3045", "exchange": "NSE"},
        "acagarwal": {"symbol": "SBIN-EQ", "token": "3045", "exchange": "NSE"},
        "motilaloswal": {"symbol": "SBIN", "token": "3045", "exchange": "NSE"},
        "kotakneo": {"symbol": "SBIN", "token": "3045", "exchange": "NSE"},
        "tradejini": {"symbol": "SBIN-EQ", "token": "3045", "exchange": "NSE"},
        "zebu": {"symbol": "SBIN-EQ", "token": "3045", "exchange": "NSE"},
        "enrichmoney": {"symbol": "SBIN-EQ", "token": "3045", "exchange": "NSE"},
    },
    "SHREECEM": {
        "zerodha": {"trading_symbol": "SHREECEM", "exchange": "NSE", "token": "11287"},
        "aliceblue": {"trading_symbol": "SHREECEM-EQ", "symbol_id": "11287", "exch": "NSE"},
        "fyers": {"symbol": "NSE:SHREECEM-EQ", "token": "11287"},
        "finvasia": {"symbol": "SHREECEM-EQ", "token": "11287", "exchange": "NSE"},
        "dhan": {"security_id": "11287", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "SHREECEM-EQ", "token": "11287", "exchange": "NSE"},
        "acagarwal": {"symbol": "SHREECEM-EQ", "token": "11287", "exchange": "NSE"},
        "motilaloswal": {"symbol": "SHREECEM", "token": "11287", "exchange": "NSE"},
        "kotakneo": {"symbol": "SHREECEM", "token": "11287", "exchange": "NSE"},
        "tradejini": {"symbol": "SHREECEM-EQ", "token": "11287", "exchange": "NSE"},
        "zebu": {"symbol": "SHREECEM-EQ", "token": "11287", "exchange": "NSE"},
        "enrichmoney": {"symbol": "SHREECEM-EQ", "token": "11287", "exchange": "NSE"},
    },
    "SUNPHARMA": {
        "zerodha": {"trading_symbol": "SUNPHARMA", "exchange": "NSE", "token": "3351"},
        "aliceblue": {"trading_symbol": "SUNPHARMA-EQ", "symbol_id": "3351", "exch": "NSE"},
        "fyers": {"symbol": "NSE:SUNPHARMA-EQ", "token": "3351"},
        "finvasia": {"symbol": "SUNPHARMA-EQ", "token": "3351", "exchange": "NSE"},
        "dhan": {"security_id": "3351", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "SUNPHARMA-EQ", "token": "3351", "exchange": "NSE"},
        "acagarwal": {"symbol": "SUNPHARMA-EQ", "token": "3351", "exchange": "NSE"},
        "motilaloswal": {"symbol": "SUNPHARMA", "token": "3351", "exchange": "NSE"},
        "kotakneo": {"symbol": "SUNPHARMA", "token": "3351", "exchange": "NSE"},
        "tradejini": {"symbol": "SUNPHARMA-EQ", "token": "3351", "exchange": "NSE"},
        "zebu": {"symbol": "SUNPHARMA-EQ", "token": "3351", "exchange": "NSE"},
        "enrichmoney": {"symbol": "SUNPHARMA-EQ", "token": "3351", "exchange": "NSE"},
    },
    "TATACONSUM": {
        "zerodha": {"trading_symbol": "TATACONSUM", "exchange": "NSE", "token": "3432"},
        "aliceblue": {"trading_symbol": "TATACONSUM-EQ", "symbol_id": "3432", "exch": "NSE"},
        "fyers": {"symbol": "NSE:TATACONSUM-EQ", "token": "3432"},
        "finvasia": {"symbol": "TATACONSUM-EQ", "token": "3432", "exchange": "NSE"},
        "dhan": {"security_id": "3432", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "TATACONSUM-EQ", "token": "3432", "exchange": "NSE"},
        "acagarwal": {"symbol": "TATACONSUM-EQ", "token": "3432", "exchange": "NSE"},
        "motilaloswal": {"symbol": "TATACONSUM", "token": "3432", "exchange": "NSE"},
        "kotakneo": {"symbol": "TATACONSUM", "token": "3432", "exchange": "NSE"},
        "tradejini": {"symbol": "TATACONSUM-EQ", "token": "3432", "exchange": "NSE"},
        "zebu": {"symbol": "TATACONSUM-EQ", "token": "3432", "exchange": "NSE"},
        "enrichmoney": {"symbol": "TATACONSUM-EQ", "token": "3432", "exchange": "NSE"},
    },
    "TATAMOTORS": {
        "zerodha": {"trading_symbol": "TATAMOTORS", "exchange": "NSE", "token": "3456"},
        "aliceblue": {"trading_symbol": "TATAMOTORS-EQ", "symbol_id": "3456", "exch": "NSE"},
        "fyers": {"symbol": "NSE:TATAMOTORS-EQ", "token": "3456"},
        "finvasia": {"symbol": "TATAMOTORS-EQ", "token": "3456", "exchange": "NSE"},
        "dhan": {"security_id": "3456", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "TATAMOTORS-EQ", "token": "3456", "exchange": "NSE"},
        "acagarwal": {"symbol": "TATAMOTORS-EQ", "token": "3456", "exchange": "NSE"},
        "motilaloswal": {"symbol": "TATAMOTORS", "token": "3456", "exchange": "NSE"},
        "kotakneo": {"symbol": "TATAMOTORS", "token": "3456", "exchange": "NSE"},
        "tradejini": {"symbol": "TATAMOTORS-EQ", "token": "3456", "exchange": "NSE"},
        "zebu": {"symbol": "TATAMOTORS-EQ", "token": "3456", "exchange": "NSE"},
        "enrichmoney": {"symbol": "TATAMOTORS-EQ", "token": "3456", "exchange": "NSE"},
    },
    "TATASTEEL": {
        "zerodha": {"trading_symbol": "TATASTEEL", "exchange": "NSE", "token": "3499"},
        "aliceblue": {"trading_symbol": "TATASTEEL-EQ", "symbol_id": "3499", "exch": "NSE"},
        "fyers": {"symbol": "NSE:TATASTEEL-EQ", "token": "3499"},
        "finvasia": {"symbol": "TATASTEEL-EQ", "token": "3499", "exchange": "NSE"},
        "dhan": {"security_id": "3499", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "TATASTEEL-EQ", "token": "3499", "exchange": "NSE"},
        "acagarwal": {"symbol": "TATASTEEL-EQ", "token": "3499", "exchange": "NSE"},
        "motilaloswal": {"symbol": "TATASTEEL", "token": "3499", "exchange": "NSE"},
        "kotakneo": {"symbol": "TATASTEEL", "token": "3499", "exchange": "NSE"},
        "tradejini": {"symbol": "TATASTEEL-EQ", "token": "3499", "exchange": "NSE"},
        "zebu": {"symbol": "TATASTEEL-EQ", "token": "3499", "exchange": "NSE"},
        "enrichmoney": {"symbol": "TATASTEEL-EQ", "token": "3499", "exchange": "NSE"},
    },
    "TECHM": {
        "zerodha": {"trading_symbol": "TECHM", "exchange": "NSE", "token": "13538"},
        "aliceblue": {"trading_symbol": "TECHM-EQ", "symbol_id": "13538", "exch": "NSE"},
        "fyers": {"symbol": "NSE:TECHM-EQ", "token": "13538"},
        "finvasia": {"symbol": "TECHM-EQ", "token": "13538", "exchange": "NSE"},
        "dhan": {"security_id": "13538", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "TECHM-EQ", "token": "13538", "exchange": "NSE"},
        "acagarwal": {"symbol": "TECHM-EQ", "token": "13538", "exchange": "NSE"},
        "motilaloswal": {"symbol": "TECHM", "token": "13538", "exchange": "NSE"},
        "kotakneo": {"symbol": "TECHM", "token": "13538", "exchange": "NSE"},
        "tradejini": {"symbol": "TECHM-EQ", "token": "13538", "exchange": "NSE"},
        "zebu": {"symbol": "TECHM-EQ", "token": "13538", "exchange": "NSE"},
        "enrichmoney": {"symbol": "TECHM-EQ", "token": "13538", "exchange": "NSE"},
    },
    "TITAN": {
        "zerodha": {"trading_symbol": "TITAN", "exchange": "NSE", "token": "3506"},
        "aliceblue": {"trading_symbol": "TITAN-EQ", "symbol_id": "3506", "exch": "NSE"},
        "fyers": {"symbol": "NSE:TITAN-EQ", "token": "3506"},
        "finvasia": {"symbol": "TITAN-EQ", "token": "3506", "exchange": "NSE"},
        "dhan": {"security_id": "3506", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "TITAN-EQ", "token": "3506", "exchange": "NSE"},
        "acagarwal": {"symbol": "TITAN-EQ", "token": "3506", "exchange": "NSE"},
        "motilaloswal": {"symbol": "TITAN", "token": "3506", "exchange": "NSE"},
        "kotakneo": {"symbol": "TITAN", "token": "3506", "exchange": "NSE"},
        "tradejini": {"symbol": "TITAN-EQ", "token": "3506", "exchange": "NSE"},
        "zebu": {"symbol": "TITAN-EQ", "token": "3506", "exchange": "NSE"},
        "enrichmoney": {"symbol": "TITAN-EQ", "token": "3506", "exchange": "NSE"},
    },
    "ULTRACEMCO": {
        "zerodha": {"trading_symbol": "ULTRACEMCO", "exchange": "NSE", "token": "2954"},
        "aliceblue": {"trading_symbol": "ULTRACEMCO-EQ", "symbol_id": "2954", "exch": "NSE"},
        "fyers": {"symbol": "NSE:ULTRACEMCO-EQ", "token": "2954"},
        "finvasia": {"symbol": "ULTRACEMCO-EQ", "token": "2954", "exchange": "NSE"},
        "dhan": {"security_id": "2954", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "ULTRACEMCO-EQ", "token": "2954", "exchange": "NSE"},
        "acagarwal": {"symbol": "ULTRACEMCO-EQ", "token": "2954", "exchange": "NSE"},
        "motilaloswal": {"symbol": "ULTRACEMCO", "token": "2954", "exchange": "NSE"},
        "kotakneo": {"symbol": "ULTRACEMCO", "token": "2954", "exchange": "NSE"},
        "tradejini": {"symbol": "ULTRACEMCO-EQ", "token": "2954", "exchange": "NSE"},
        "zebu": {"symbol": "ULTRACEMCO-EQ", "token": "2954", "exchange": "NSE"},
        "enrichmoney": {"symbol": "ULTRACEMCO-EQ", "token": "2954", "exchange": "NSE"},
    },
    "UPL": {
        "zerodha": {"trading_symbol": "UPL", "exchange": "NSE", "token": "11287"},
        "aliceblue": {"trading_symbol": "UPL-EQ", "symbol_id": "11287", "exch": "NSE"},
        "fyers": {"symbol": "NSE:UPL-EQ", "token": "11287"},
        "finvasia": {"symbol": "UPL-EQ", "token": "11287", "exchange": "NSE"},
        "dhan": {"security_id": "11287", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "UPL-EQ", "token": "11287", "exchange": "NSE"},
        "acagarwal": {"symbol": "UPL-EQ", "token": "11287", "exchange": "NSE"},
        "motilaloswal": {"symbol": "UPL", "token": "11287", "exchange": "NSE"},
        "kotakneo": {"symbol": "UPL", "token": "11287", "exchange": "NSE"},
        "tradejini": {"symbol": "UPL-EQ", "token": "11287", "exchange": "NSE"},
        "zebu": {"symbol": "UPL-EQ", "token": "11287", "exchange": "NSE"},
        "enrichmoney": {"symbol": "UPL-EQ", "token": "11287", "exchange": "NSE"},
    },
    "WIPRO": {
        "zerodha": {"trading_symbol": "WIPRO", "exchange": "NSE", "token": "3787"},
        "aliceblue": {"trading_symbol": "WIPRO-EQ", "symbol_id": "3787", "exch": "NSE"},
        "fyers": {"symbol": "NSE:WIPRO-EQ", "token": "3787"},
        "finvasia": {"symbol": "WIPRO-EQ", "token": "3787", "exchange": "NSE"},
        "dhan": {"security_id": "3787", "exchange_segment": "NSE_EQ"},
        "flattrade": {"symbol": "WIPRO-EQ", "token": "3787", "exchange": "NSE"},
        "acagarwal": {"symbol": "WIPRO-EQ", "token": "3787", "exchange": "NSE"},
        "motilaloswal": {"symbol": "WIPRO", "token": "3787", "exchange": "NSE"},
        "kotakneo": {"symbol": "WIPRO", "token": "3787", "exchange": "NSE"},
        "tradejini": {"symbol": "WIPRO-EQ", "token": "3787", "exchange": "NSE"},
        "zebu": {"symbol": "WIPRO-EQ", "token": "3787", "exchange": "NSE"},
        "enrichmoney": {"symbol": "WIPRO-EQ", "token": "3787", "exchange": "NSE"},
    },
    # End of Nifty 50 list.
}

def get_symbol_for_broker(symbol, broker):
    symbol = symbol.upper()
    broker = broker.lower()
    return SYMBOL_MAP.get(symbol, {}).get(broker, {})
