services:
  - type: web
    name: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL
  - type: worker
    name: scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A services.scheduler beat --loglevel=info
    envVars:
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL
  - type: worker
    name: worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A task.celery worker --loglevel=info
    envVars:
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL
